name = "Planck"
uuid = "49ffdefc-b0d8-4915-a1d4-43900e16f762"
authors = ["Miles Lucas <mdlucas@hawaii.edu> and contributors"]
version = "0.1.0"

[deps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Unitful = "1"
julia = "1.6"
